[toolchain]
anchor_version = "0.32.1"

[programs.localnet]
argus_registry = "STmkbEWTmfBJR2mDHrbvKNjo2spT6mPU9668mw2hMaL"

[programs.devnet]
argus_registry = "STmkbEWTmfBJR2mDHrbvKNjo2spT6mPU9668mw2hMaL"

[provider]
cluster = "devnet"
wallet = ".argus-devnet-keypair.json"
